-- MySQL Script generated by MySQL Workbench
-- Wed Aug 22 07:45:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NOT NULL,
  `representante` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `rfc` VARCHAR(45) NULL,
  `curp` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `celular` VARCHAR(20) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(100) NULL,
  `cp` INT NOT NULL,
  `domicilio` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidad_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidad_compra` (
  `id_unidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha_fin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_venta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `id_pedidos` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL DEFAULT 0,
  `importe` INT NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  `id_cliente` INT UNSIGNED NOT NULL,
  `id_venta` INT NOT NULL,
  PRIMARY KEY (`id_pedidos`),
  INDEX `fk_pedidos_clientes1_idx` (`id_cliente` ASC),
  INDEX `fk_pedidos_ventas1_idx` (`id_venta` ASC),
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_ventas1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `mydb`.`ventas` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articulos` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  `id_unidad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `id_pedidos` INT NOT NULL,
  PRIMARY KEY (`id_articulo`),
  INDEX `fk_articulos_categorias1_idx` (`id_categoria` ASC),
  INDEX `fk_articulos_departamentos1_idx` (`id_departamento` ASC),
  INDEX `fk_articulos_unidad_compra1_idx` (`id_unidad` ASC),
  INDEX `fk_articulos_pedidos1_idx` (`id_pedidos` ASC),
  CONSTRAINT `fk_articulos_categorias1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_unidad_compra1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `mydb`.`unidad_compra` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_pedidos1`
    FOREIGN KEY (`id_pedidos`)
    REFERENCES `mydb`.`pedidos` (`id_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actual` INT NOT NULL DEFAULT 0,
  `nueva` INT NOT NULL DEFAULT 0,
  `diferencia` INT NOT NULL DEFAULT 0,
  `id_articulo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventario_articulos1_idx` (`id_articulo` ASC),
  CONSTRAINT `fk_inventario_articulos1`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `mydb`.`articulos` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
